### PR TITLE
Updated cookbook to be compatible with latest Chef version

### PR DESCRIPTION
**Pull request by russelltrow**
Added a name attribute to the cookbooks metadata

### CODE REVIEW

**Comment by josephholsten** [comment]
I'd rather it was lowercase, does that work with you @russelltrow?

**Comment by russelltrow** [comment]
Hi Joseph, I've made the name lowercase and matched the repository name. How is that?

**Comment by monfresh** [comment]
Hi. Any idea when this will be merged and released? Is there something that is preventing this from being merged?

**Comment by zuazo** [comment]
@russelltrow I think it should be `name 'nano'` instead of `name 'nano-cookbook'`. See [here](https://github.com/chef-brigade/nano-cookbook/blob/14a47404fcb6c34cf7b2cbe7d8c957789eb5652e/recipes/default.rb#L2).

**Comment by josephholsten** [comment]
merged manually

**Pull request closed without merging**
